# Generated by Django 4.0.6 on 2022-07-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='trackedbook',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_book_tracker'),
        ),
    ]
