# Generated by Django 4.0.6 on 2022-07-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='featured',
            field=models.BooleanField(),
        ),
    ]
